"""empty message

Revision ID: 9329be9ae774
Revises: 287b54acbf78
Create Date: 2024-05-08 11:41:18.916398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9329be9ae774'
down_revision = '287b54acbf78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tienda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_tienda', sa.String(length=120), nullable=False),
    sa.Column('descripcion_tienda', sa.String(length=500), nullable=True),
    sa.Column('categoria_tienda', sa.String(length=80), nullable=False),
    sa.Column('direccion_tienda', sa.String(length=120), nullable=False),
    sa.Column('url_imagen_tienda', sa.String(length=120), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vendedor_id'], ['vendedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_producto', sa.String(length=120), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.Column('descripcion_producto', sa.String(length=500), nullable=True),
    sa.Column('categoria_producto', sa.String(length=80), nullable=False),
    sa.Column('url_imagen_producto', sa.String(length=120), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=True),
    sa.Column('tienda_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tienda_id'], ['tienda.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['vendedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.drop_table('producto')
    op.drop_table('tienda')
    op.drop_table('vendedor')
    # ### end Alembic commands ###
