"""empty message

Revision ID: a81c000c7328
Revises: 9329be9ae774
Create Date: 2024-05-08 12:21:29.624545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a81c000c7328'
down_revision = '9329be9ae774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tienda', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombre_tienda'])

    with op.batch_alter_table('vendedor', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))

    with op.batch_alter_table('tienda', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
